/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 */

package com.mycompany.part2poe;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Scanner;

public class Part2Poe {

    //Message Details
    static class MessageDetails {
        String messageId;
        String messageHash;
        String recipient;
        String messageText;

        public MessageDetails(String messageId, String messageHash, String recipient, String messageText) {
            this.messageId = messageId;
            this.messageHash = messageHash;
            this.recipient = recipient;
            this.messageText = messageText;
        }
    }

    private static final Scanner scanner = new Scanner(System.in);
    private static final Random random = new Random();
    private static int totalMessagesSentCounter = 0; // Tracks global sequential messages autogenerated count

    public static void main(String[] args) {
        // Requirement 1: User must be successfully logged in to send messages
        if (!performLogin()) {
            System.out.println("Login failed. Exiting application.");
            return;
        }

        boolean running = true;
        while (running) {
            // Requirement 2: Display welcome message and menu
            System.out.println("\n=================================");
            System.out.println("Welcome to QuickChat.");
            System.out.println("=================================");
            System.out.println("1) Send Messages");
            System.out.println("2) Show recently sent messages – this feature is still in development and should display the following message: \"Coming Soon.\"");
            System.out.println("3) Quit");
            System.out.print("Please choose an option (1-3): ");

            String choice = scanner.nextLine().trim();

            switch (choice) {
                case "1":
                    handleSendMessagesFlow();
                    break;
                case "2":
                    System.out.println("\nComing Soon.");
                    break;
                case "3":
                    // Requirement 4: Application runs until 'quit' is selected
                    System.out.println("Thank you for using QuickChat. Goodbye!");
                    running = false;
                    break;
                default:
                    System.out.println("Invalid option. Please enter 1, 2, or 3.");
            }
        }
    }

        private static boolean performLogin() {
        System.out.println("--- QuickChat Login System ---");
        System.out.print("Enter username: ");
        String username = scanner.nextLine();
        System.out.print("Enter password: ");
        String password = scanner.nextLine();
        
        // Simulating a successful login
        return !username.isEmpty() && !password.isEmpty();
    }

        private static void handleSendMessagesFlow() {
        // Requirement 5: Users should define how many messages they wish to enter
        System.out.print("\nHow many messages would you like to enter? ");
        int numberOfMessagesToProcess;
        try {
            numberOfMessagesToProcess = Integer.parseInt(scanner.nextLine().trim());
            if (numberOfMessagesToProcess <= 0) {
                System.out.println("Please enter a number greater than 0.");
                return;
            }
        } catch (NumberFormatException e) {
            System.out.println("Invalid number format. Returning to main menu.");
            return;
        }

        List<MessageDetails> sessionMessages = new ArrayList<>();
        int successfullySentInSessionCount = 0;

        for (int i = 0; i < numberOfMessagesToProcess; i++) {
            System.out.println("\n--- Processing Message " + (i + 1) + " of " + numberOfMessagesToProcess + " ---");

            // --- 1. Generate Unique Message ID ---
            // Requirement: Randomly generated ten-digit number string
            String messageId = generateRandomTenDigitId();

            // --- 2. Recipient Validation ---
            // Requirement: Cell number, no more than 10 characters, contains international code
            String recipient = "";
            while (true) {
                System.out.print("Enter Recipient Cell Number (Max 10 chars, include international code prefix): ");
                recipient = scanner.nextLine().trim();
                if (recipient.length() <= 10 && !recipient.isEmpty()) {
                    break;
                } else {
                    System.out.println("Invalid entry. The cell number must not exceed 10 characters.");
                }
            }

            // --- 3. Message Text Validation ---
            // Requirement: Should not exceed 250 characters. Show custom message rules if too long.
            String messageText = "";
            while (true) {
                System.out.print("Enter Message (Max 250 characters): ");
                messageText = scanner.nextLine().trim();
                if (messageText.length() > 250) {
                    System.out.println("\"Please enter a message of less than 250 characters.\"");
                } else {
                    break;
                }
            }

                        String messageHash = generateMessageHash(messageId, totalMessagesSentCounter, messageText);

            // --- 5. Post-Completion Options Menu ---
            // Requirement Table: Once completed, ask user to select Send, Disregard, or Store
            System.out.println("\nChoose one of the following options for this message:");
            System.out.println("1. Send Message");
            System.out.println("2. Disregard Message");
            System.out.println("3. Store Message to send later");
            System.out.print("Selection: ");
            String actionChoice = scanner.nextLine().trim();

            if (actionChoice.equals("1")) {
                // Sent Status
                System.out.println("\n\"Message successfully sent\"");
                totalMessagesSentCounter++;
                successfullySentInSessionCount++;

                // Save to local print stack
                MessageDetails msgDetails = new MessageDetails(messageId, messageHash, recipient, messageText);
                sessionMessages.add(msgDetails);

                // Requirement 7: The full details of each message should be displayed on screen after it has been sent
                // Order: Message ID, Message Hash, Recipient, Message.
                System.out.println("\n>>> SENT MESSAGE SUMMARY RECIPIENT RECORD <<<");
                System.out.println("Message ID:   " + msgDetails.messageId);
                System.out.println("Message Hash: " + msgDetails.messageHash);
                System.out.println("Recipient:    " + msgDetails.recipient);
                System.out.println("Message:      " + msgDetails.messageText);
                System.out.println("---------------------------------------------");

            } else if (actionChoice.equals("2") || actionChoice.equals("0")) {
                // Disregard Status
                System.out.println("\n\"Press 0 to delete the message\"");
                System.out.println("Message discarded.");
            } else if (actionChoice.equals("3")) {
                // Store Status
                System.out.println("\n\"Message successfully stored\"");
                System.out.println("(Note: Store Message in a JSON file feature is categorized under Research/Future Work)");
            } else {
                System.out.println("Invalid option. Action cancelled, message disregarded.");
            }
        }

        // Requirement 6: The total number of messages should be accumulated and displayed once all messages have been sent
        System.out.println("\n=========================================");
        System.out.println("Session Summary Completed!");
        System.out.println("Messages successfully sent this batch: " + successfullySentInSessionCount);
        System.out.println("Total global application messages sent: " + totalMessagesSentCounter);
        System.out.println("=========================================");
    }

    /**
     * Helper to generate a random 10-digit numeric ID string
     */
    private static String generateRandomTenDigitId() {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < 10; i++) {
            sb.append(random.nextInt(10));
        }
        return sb.toString();
    }

        private static String generateMessageHash(String messageId, int numSent, String messageText) {
        String firstTwoDigits = messageId.substring(0, 2);
        
        // Sanitize string to clean multi-spaces for extracting words safely
        String cleanedText = messageText.trim().replaceAll("\\s+", " ");
        String wordsCombined = "";

        if (!cleanedText.isEmpty()) {
            String[] words = cleanedText.split(" ");
            String firstWord = words[0];
            String lastWord = words[words.length - 1];
            
            // Format strictly requires text string smashed together in all-caps
            wordsCombined = (firstWord + lastWord).toUpperCase();
            // Remove punctuation formatting from words if any, keeping it uniform
            wordsCombined = wordsCombined.replaceAll("[^A-Z0-9]", ""); 
        } else {
            wordsCombined = "EMPTYMESSAGE";
        }

        return firstTwoDigits + ":" + numSent + ":" + wordsCombined;
    }
}